baseURL = "https://blog.sophie-eden.ltd/"
title = "迷锁魔方"
copyright = "Sophie Eden"
# 默认每页列表显示的文章数目
pagination.pagerSize = 30

DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-cn"
# 自动检测是否包含中文/日文/韩文，该参数会影响摘要和字数统计功能，建议设置为true
hasCJKLanguage =  true
theme = "hugo-theme-diary"

# googleAnalytics = "UA-123-45"

[params]
subtitle = "不确定之物的终点站·聆听万物之声·资讯统合思念体·薛定谔的猫"
keywords = ["摘录", "资讯"]
enableGitalk = false
enableReadingTime=true

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "迷锁魔方" # will set 'og:site_name'
description = "不确定之物的终点站·聆听万物之声·资讯统合思念体·薛定谔的猫"  # will set 'og:description'
Favicon = "images/favicon.ico"

[markup]

  # Goldmark 渲染器默认不渲染 HTML tags。启用非安全模式，嵌入html标签。
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
  #  style = "monokai"
  #  style = ""
    tabWidth = 4

[params.gitalk]
  owner = "yamaeye"
  repo = "talks"
  client_id = "Iv1.a1a99f28af941e30"
  client_secret = "fcb1d08dc0370cc647a3de8f3db00d666089773f"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"



[taxonomies]
   tag = "tags"
   category = "categories"

[Permalinks]
  diary = "diary/:year/:month/:day/:title"
# posts = ":filename"

[[menu.main]]
url = "/chat"
name = "碎碎念"
weight = 10

[[menu.main]]
url = "/diary"
name = "随笔"
weight = 20

[[menu.main]]
url = "/thoughts"
name = "思考"
weight = 30

[[menu.main]]
url = "/categories"
name = "专栏"
weight = 40

[[menu.main]]
url = "/tags"
name = "标签"
weight = 50

[[menu.main]]
url = "/story"
name = "幻视"
weight = 60

[[menu.main]]
url = "http://sophie-eden.ltd/"
name = "导航"
weight = 100

[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 200
